language: python
python:
  - "3.4"
  - "3.5"
env:
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="https://github.com/django/django/archive/master.tar.gz"
install:
  - pip install -q $DJANGO
script:
  - python -Wall tests/manage.py test core --settings=
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="Django>=1.9,<1.10"
    - python: "3.3"
      env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
    - python: "3.5"
      env: DJANGO="Django>=1.7,<1.8"
  allow_failures:
    - env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
